import { useParams, useNavigate } from "react-router-dom"
import { useState, useEffect } from "react"
import useSEO from "../utils/useSEO"

const PACKAGE_DATA = {
  kasi: { name: "Kasi Yatra", subtitle: "Varanasi - Prayagraj - Ayodhya", price: "35,999", rawPrice: 35999, days: "6 Days / 5 Nights", badge: "MOST POPULAR", badgeColor: "#ec4899", img: "https://images.unsplash.com/photo-1561361058-c24cecae35ca?w=600&q=80", about: "Varanasi is one of the world oldest living cities and the spiritual capital of India.", experience: [{ icon: "sun", title: "Ganga Aarti", desc: "Witness the Ganga Aarti at Dashashwamedh Ghat" },{ icon: "temple", title: "Kashi Vishwanath", desc: "Seek blessings at Kashi Vishwanath" },{ icon: "boat", title: "Ganga Boat Ride", desc: "Early morning boat ride on the Ganga" },{ icon: "pray", title: "Triveni Sangam", desc: "Holy dip at Prayagraj Sangam" },{ icon: "temple2", title: "Ram Mandir", desc: "Visit the newly built Ram Mandir in Ayodhya" },{ icon: "wheel", title: "Sarnath", desc: "Explore Sarnath" }], gallery: ["https://images.unsplash.com/photo-1561361058-c24cecae35ca?w=600&q=80","https://images.unsplash.com/photo-1561361058-c24cecae35ca?w=600&q=80","https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?w=600&q=80","/chardam.png","https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=600&q=80","https://images.unsplash.com/photo-1544735716-392fe2489ffa?w=600&q=80"], inclusions: ["5 nights accommodation","Daily breakfast & dinner","AC vehicle","Expert guide","Temple entry arrangements","Boat ride on Ganga","Flight tickets / Train tickets"], exclusions: ["Auto charge","VIP Darshan","Personal expenses"], itinerary: [{ day: "Day 1", title: "Arrival in Varanasi", desc: "Arrive at Varanasi. Check-in. Evening Ganga Aarti." },{ day: "Day 2", title: "Kashi Vishwanath & Ghats", desc: "Boat ride on Ganga. Visit Kashi Vishwanath Temple." },{ day: "Day 3", title: "Sarnath", desc: "Visit Sarnath - Dhamek Stupa, Sarnath Museum." },{ day: "Day 4", title: "Prayagraj", desc: "Drive to Prayagraj. Visit Triveni Sangam." },{ day: "Day 5", title: "Ayodhya", desc: "Drive to Ayodhya. Visit Ram Mandir." },{ day: "Day 6", title: "Departure", desc: "Transfer to airport/station." }] },
  chardham: { name: "Chardham Yatra", subtitle: "Yamunotri - Gangotri - Kedarnath - Badrinath", price: "79,999", rawPrice: 79999, days: "12 Days / 11 Nights", badge: "BEST VALUE", badgeColor: "#14b8a6", img: "https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?w=1200&q=80", about: "The Chardham Yatra is the most sacred pilgrimage in Hinduism - a journey to four divine shrines in the Garhwal Himalayas.", experience: [{ icon: "mountain", title: "Kedarnath Trek", desc: "Trek through breathtaking Himalayan landscapes" },{ icon: "wave", title: "Gangotri Origin", desc: "Witness the origin of the sacred Ganga at Gangotri" },{ icon: "temple", title: "Badrinath Darshan", desc: "Seek blessings at Badrinath" },{ icon: "sunrise", title: "Himalayan Sunrise", desc: "Watch the golden sunrise over snow-capped peaks" },{ icon: "pray", title: "Tapt Kund", desc: "Holy dip in the Tapt Kund hot spring at Badrinath" },{ icon: "leaf", title: "Mana Village", desc: "Experience Mana village - the last Indian village before Tibet" }], gallery: ["/chardam.png","https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=600&q=80","https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?w=600&q=80","https://images.unsplash.com/photo-1561361058-c24cecae35ca?w=600&q=80","https://images.unsplash.com/photo-1544735716-392fe2489ffa?w=600&q=80","https://images.unsplash.com/photo-1476514525535-07fb3b4ae5f1?w=600&q=80"], inclusions: ["11 nights accommodation","All meals","AC vehicle","Yatra guide","Pony/palki at Kedarnath","Medical kit & oxygen","Flight tickets / Train tickets"], exclusions: ["Auto charge","VIP Darshan","Personal expenses"], itinerary: [{ day: "Day 1", title: "Arrival Haridwar", desc: "Arrive at Haridwar. Evening Ganga Aarti at Har Ki Pauri." },{ day: "Day 2", title: "Haridwar to Barkot", desc: "Drive to Barkot via Rishikesh, Chamba, Uttarkashi." },{ day: "Day 3", title: "Yamunotri Darshan", desc: "Trek 6km to Yamunotri Temple. Holy dip in Surya Kund." },{ day: "Day 4", title: "Barkot to Uttarkashi", desc: "Drive to Uttarkashi. Visit Vishwanath Temple." },{ day: "Day 5", title: "Gangotri Darshan", desc: "Drive to Gangotri. Temple darshan, holy dip in Bhagirathi River." },{ day: "Day 6", title: "Uttarkashi to Guptkashi", desc: "Long drive through scenic Himalayan roads." },{ day: "Day 7", title: "Kedarnath Darshan", desc: "Trek/pony to Kedarnath (14km). Evening darshan." },{ day: "Day 8", title: "Kedarnath to Badrinath", desc: "Morning darshan, trek down. Drive to Badrinath." },{ day: "Day 9", title: "Badrinath Darshan", desc: "Tapt Kund dip, Badrinath Temple darshan. Visit Mana village." },{ day: "Day 10", title: "Badrinath to Rudraprayag", desc: "Drive back through Himalayan valleys." },{ day: "Day 11", title: "Rudraprayag to Haridwar", desc: "Drive to Haridwar. Evening free." },{ day: "Day 12", title: "Departure", desc: "Morning Ganga Aarti. Transfer to airport/station." }] },
  nepal: { name: "Nepal Tour", subtitle: "Kathmandu - Pokhara - Pashupatinath - Muktinath - Sonali", price: "57,999", rawPrice: 57999, days: "9 Days / 8 Nights", badge: "RECOMMENDED", badgeColor: "#0d9488", img: "https://images.unsplash.com/photo-1544735716-392fe2489ffa?w=1200&q=80", about: "Nepal is the land of the Himalayas, ancient temples, and spiritual energy. Home to 8 of the world highest peaks including Mount Everest. Visit the sacred Pashupatinath Temple, Muktinath Dham, and the India-Nepal border town of Sonali.", experience: [{ icon: "mountain", title: "Sarangkot Sunrise", desc: "Golden sunrise over the Annapurna range from Sarangkot" },{ icon: "temple", title: "Pashupatinath", desc: "Seek blessings at Pashupatinath - the most sacred Shiva temple outside India" },{ icon: "wheel", title: "Boudhanath Stupa", desc: "Circumambulate the massive Boudhanath Stupa" },{ icon: "wave", title: "Phewa Lake", desc: "Peaceful boat ride on Phewa Lake" },{ icon: "monkey", title: "Monkey Temple", desc: "Visit Swayambhunath - an ancient Buddhist shrine" },{ icon: "leaf", title: "Bhaktapur", desc: "Explore ancient Newari architecture in Bhaktapur" }], gallery: ["https://images.unsplash.com/photo-1544735716-392fe2489ffa?w=600&q=80","https://images.unsplash.com/photo-1476514525535-07fb3b4ae5f1?w=600&q=80","https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=600&q=80","https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?w=600&q=80","https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=600&q=80","/chardam.png"], inclusions: ["6 nights accommodation","Daily breakfast & dinner","AC vehicle","Expert guide","Monument entry fees","Boat ride on Phewa Lake","Nepal visa assistance","Flight tickets / Train tickets"], exclusions: ["Auto charge","VIP Darshan","Personal expenses"], itinerary: [{ day: "Day 1", title: "Arrival Kathmandu", desc: "Arrive at Tribhuvan International Airport. Evening - Thamel market walk." },{ day: "Day 2", title: "Kathmandu Temples", desc: "Visit Pashupatinath Temple, Boudhanath Stupa, Swayambhunath." },{ day: "Day 3", title: "Bhaktapur & Patan", desc: "Full day tour of Bhaktapur Durbar Square (UNESCO), Patan Durbar Square." },{ day: "Day 4", title: "Kathmandu to Pokhara", desc: "Drive/fly to Pokhara. Phewa Lake boat ride, Barahi Temple." },{ day: "Day 5", title: "Sarangkot Sunrise", desc: "Early morning drive to Sarangkot for Himalayan sunrise." },{ day: "Day 6", title: "Pokhara to Kathmandu", desc: "Return to Kathmandu. Free time for shopping. Farewell dinner." },{ day: "Day 7", title: "Departure", desc: "Transfer to airport. Depart with beautiful Himalayan memories." }] },
  tirupati: { name: "Tirupati Darshan", subtitle: "Tirupati - Tirumala", price: "12,999", rawPrice: 12999, days: "3 Days / 2 Nights", badge: "DEVOTION", badgeColor: "#f59e0b", img: "https://images.unsplash.com/photo-1609766418204-94aae0ecfdfc?w=1200&q=80", about: "Tirupati is home to the Venkateswara Temple - the most visited religious site in the world. Lord Venkateswara (Balaji) is believed to fulfill the wishes of all devotees.", experience: [{ icon: "temple", title: "Venkateswara Darshan", desc: "Seek blessings at the most visited temple in the world" },{ icon: "hill", title: "Tirumala Hills", desc: "Scenic drive up the seven hills to reach the sacred Tirumala temple complex" },{ icon: "pray", title: "Padmavathi Temple", desc: "Visit Goddess Padmavathi Temple" },{ icon: "water", title: "Kapila Theertham", desc: "Holy dip at Kapila Theertham - sacred waterfall at the base of Tirumala" },{ icon: "flower", title: "Prasadam", desc: "Receive the famous Tirupati Laddu prasadam" },{ icon: "fort", title: "Chandragiri Fort", desc: "Visit the historic Chandragiri Fort" }], gallery: ["https://images.unsplash.com/photo-1609766418204-94aae0ecfdfc?w=600&q=80","https://images.unsplash.com/photo-1519451241324-20b4ea2c4220?w=600&q=80","https://images.unsplash.com/photo-1561361058-c24cecae35ca?w=600&q=80","https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?w=600&q=80","/chardam.png","https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=600&q=80"], inclusions: ["2 nights accommodation","Daily breakfast","AC vehicle","Expert guide","Darshan ticket arrangements","Prasadam","Flight tickets / Train tickets"], exclusions: ["Auto charge","VIP Darshan","Personal expenses"], itinerary: [{ day: "Day 1", title: "Arrival Tirupati", desc: "Arrive at Tirupati. Check-in. Evening - visit Kapila Theertham and Padmavathi Temple." },{ day: "Day 2", title: "Tirumala Darshan", desc: "Early morning drive to Tirumala. Venkateswara Temple darshan. Receive Tirupati Laddu prasadam." },{ day: "Day 3", title: "Departure", desc: "Morning visit to Chandragiri Fort. Transfer to station/airport." }] },
  rameswaram: { name: "Rameswaram & Madurai", subtitle: "Rameswaram - Madurai - Kanyakumari", price: "14,999", rawPrice: 14999, days: "4 Days / 3 Nights", badge: "SOUTH INDIA", badgeColor: "#7c3aed", img: "https://images.unsplash.com/photo-1519451241324-20b4ea2c4220?w=1200&q=80", about: "Rameswaram is one of the Char Dham pilgrimage sites. The Ramanathaswamy Temple has the longest corridor of any temple in India. Madurai Meenakshi Amman Temple is a masterpiece of Dravidian architecture.", experience: [{ icon: "temple", title: "Ramanathaswamy Temple", desc: "Visit the magnificent temple with the longest corridor in India - 1212 pillars" },{ icon: "wave", title: "Agni Theertham", desc: "Holy dip in the sea at Agni Theertham" },{ icon: "fort", title: "Meenakshi Temple", desc: "Marvel at the stunning Meenakshi Amman Temple" },{ icon: "sunrise", title: "Kanyakumari Sunrise", desc: "Watch the breathtaking sunrise where three seas meet" },{ icon: "rock", title: "Vivekananda Rock", desc: "Visit the Vivekananda Rock Memorial" },{ icon: "bridge", title: "Pamban Bridge", desc: "Cross the iconic Pamban Bridge" }], gallery: ["https://images.unsplash.com/photo-1519451241324-20b4ea2c4220?w=600&q=80","https://images.unsplash.com/photo-1582510003544-4d00b7f74220?w=600&q=80","https://images.unsplash.com/photo-1561361058-c24cecae35ca?w=600&q=80","https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?w=600&q=80","https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=600&q=80","https://images.unsplash.com/photo-1476514525535-07fb3b4ae5f1?w=600&q=80"], inclusions: ["3 nights accommodation","Daily breakfast","AC vehicle","Expert guide","All temple entry arrangements","Flight tickets / Train tickets"], exclusions: ["Auto charge","VIP Darshan","Personal expenses"], itinerary: [{ day: "Day 1", title: "Arrival Rameswaram", desc: "Arrive at Rameswaram. Check-in. Visit Agni Theertham, Ramanathaswamy Temple darshan." },{ day: "Day 2", title: "Rameswaram Sightseeing", desc: "Visit Dhanushkodi, Pamban Bridge, Kothandaramaswamy Temple." },{ day: "Day 3", title: "Madurai", desc: "Drive to Madurai. Visit Meenakshi Amman Temple, Thirumalai Nayakkar Palace." },{ day: "Day 4", title: "Kanyakumari & Departure", desc: "Drive to Kanyakumari. Sunrise view, Vivekananda Rock, Thiruvalluvar Statue. Departure." }] },
  andaman: { name: "Andaman Islands", subtitle: "Port Blair - Havelock - Neil Island", price: "45,000", rawPrice: 45000, days: "6 Days / 5 Nights", badge: "BEACH PARADISE", badgeColor: "#0891b2", img: "https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=1200&q=80", about: "The Andaman Islands are a tropical paradise in the Bay of Bengal - pristine white sand beaches, crystal clear turquoise waters, and vibrant coral reefs.", experience: [{ icon: "beach", title: "Radhanagar Beach", desc: "Relax on Radhanagar Beach - rated one of Asia best beaches" },{ icon: "dive", title: "Scuba Diving", desc: "Explore vibrant coral reefs and marine life" },{ icon: "fish", title: "Snorkeling", desc: "Snorkel in crystal clear waters" },{ icon: "jail", title: "Cellular Jail", desc: "Visit the historic Cellular Jail" },{ icon: "boat", title: "Glass Bottom Boat", desc: "See the underwater world on a glass bottom boat ride" },{ icon: "island", title: "Neil Island", desc: "Explore the serene Neil Island" }], gallery: ["https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=600&q=80","https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=600&q=80","https://images.unsplash.com/photo-1519451241324-20b4ea2c4220?w=600&q=80","https://images.unsplash.com/photo-1476514525535-07fb3b4ae5f1?w=600&q=80","https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?w=600&q=80","https://images.unsplash.com/photo-1587922546307-776227941871?w=600&q=80"], inclusions: ["5 nights accommodation","Daily breakfast & dinner","All ferry transfers","AC vehicle transfers","Scuba diving (1 session)","Cellular Jail light & sound show","Flight tickets / Train tickets"], exclusions: ["Auto charge","VIP Darshan","Personal expenses"], itinerary: [{ day: "Day 1", title: "Arrival Port Blair", desc: "Arrive at Port Blair. Check-in. Visit Cellular Jail, evening Light & Sound Show." },{ day: "Day 2", title: "Port Blair Sightseeing", desc: "Visit Corbyn Cove Beach, Samudrika Marine Museum, Ross Island." },{ day: "Day 3", title: "Havelock Island", desc: "Ferry to Havelock. Afternoon - Radhanagar Beach. Sunset views." },{ day: "Day 4", title: "Havelock Activities", desc: "Morning scuba diving / snorkeling at Elephant Beach." },{ day: "Day 5", title: "Neil Island", desc: "Ferry to Neil Island. Visit Natural Bridge, Bharatpur Beach. Return to Port Blair." },{ day: "Day 6", title: "Departure", desc: "Morning free. Transfer to airport." }] },
  golden_triangle: { name: "Golden Triangle", subtitle: "Delhi - Agra - Jaipur", price: "33,000", rawPrice: 33000, days: "6 Days / 5 Nights", badge: "HERITAGE", badgeColor: "#d97706", img: "https://images.unsplash.com/photo-1564507592333-c60657eea523?w=1200&q=80", about: "The Golden Triangle is India most famous tourist circuit connecting Delhi, Agra, and Jaipur. Agra is home to the Taj Mahal - one of the Seven Wonders of the World.", experience: [{ icon: "mosque", title: "Taj Mahal", desc: "Stand before the Taj Mahal at sunrise" },{ icon: "fort", title: "Amber Fort", desc: "Explore the magnificent Amber Fort in Jaipur" },{ icon: "minaret", title: "Qutub Minar", desc: "Visit the UNESCO World Heritage Qutub Minar" },{ icon: "elephant", title: "Elephant Ride", desc: "Traditional elephant ride up to Amber Fort" },{ icon: "shop", title: "Jaipur Bazaars", desc: "Shop for gems, textiles, and handicrafts in Jaipur" },{ icon: "sunrise", title: "Agra Fort", desc: "Visit the massive Agra Fort" }], gallery: ["https://images.unsplash.com/photo-1564507592333-c60657eea523?w=600&q=80","https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?w=600&q=80","https://images.unsplash.com/photo-1476514525535-07fb3b4ae5f1?w=600&q=80","https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=600&q=80","https://images.unsplash.com/photo-1519451241324-20b4ea2c4220?w=600&q=80","https://images.unsplash.com/photo-1561361058-c24cecae35ca?w=600&q=80"], inclusions: ["5 nights accommodation","Daily breakfast","AC vehicle","Expert guide","All monument entry fees","Elephant ride at Amber Fort","Flight tickets / Train tickets"], exclusions: ["Auto charge","VIP Darshan","Personal expenses"], itinerary: [{ day: "Day 1", title: "Arrival Delhi", desc: "Arrive at Delhi. Check-in. Evening - India Gate, Connaught Place." },{ day: "Day 2", title: "Delhi Sightseeing", desc: "Visit Qutub Minar, Humayun Tomb, Red Fort, Jama Masjid, Chandni Chowk." },{ day: "Day 3", title: "Delhi to Agra", desc: "Drive to Agra. Afternoon - Taj Mahal at sunset, Agra Fort." },{ day: "Day 4", title: "Agra to Jaipur", desc: "Early morning Taj Mahal sunrise visit. Drive to Jaipur via Fatehpur Sikri." },{ day: "Day 5", title: "Jaipur Sightseeing", desc: "Visit Amber Fort (elephant ride), City Palace, Jantar Mantar, Hawa Mahal." },{ day: "Day 6", title: "Departure", desc: "Morning free for shopping. Transfer to airport/station." }] },
  kailash: { name: "Kailash Mansarovar", subtitle: "Sacred Himalayan Pilgrimage", price: "2,75,000", rawPrice: 275000, days: "15+ Days", badge: "PREMIUM", badgeColor: "#7c3aed", img: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=1200&q=80", about: "Kailash Mansarovar Yatra is the most sacred pilgrimage in Hinduism, Buddhism, Jainism, and Bon religion. Mount Kailash (6638m) is believed to be the abode of Lord Shiva.", experience: [{ icon: "mountain", title: "Mt. Kailash Parikrama", desc: "Complete the sacred 52km circumambulation of Mt. Kailash" },{ icon: "lake", title: "Mansarovar Lake", desc: "Holy dip in Lake Mansarovar - the highest freshwater lake in the world at 4590m" },{ icon: "pray", title: "Shiva Abode", desc: "Stand before Mt. Kailash - believed to be the cosmic axis and abode of Lord Shiva" },{ icon: "sunrise", title: "Himalayan Vistas", desc: "Breathtaking views of the Himalayas, Karakoram, and Hindu Kush ranges" },{ icon: "wheel", title: "Tibetan Culture", desc: "Immerse in ancient Tibetan Buddhist culture, monasteries, and traditions" },{ icon: "leaf", title: "Spiritual Transformation", desc: "Experience a profound spiritual transformation on this once-in-a-lifetime journey" }], gallery: ["https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=600&q=80","/chardam.png","https://images.unsplash.com/photo-1544735716-392fe2489ffa?w=600&q=80","https://images.unsplash.com/photo-1476514525535-07fb3b4ae5f1?w=600&q=80","https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?w=600&q=80","https://images.unsplash.com/photo-1561361058-c24cecae35ca?w=600&q=80"], inclusions: ["All accommodation (hotels & camps)","All meals","All transfers & permits","Experienced yatra guide","Medical support & oxygen","Tibet travel permit","Flight tickets / Train tickets"], exclusions: ["Auto charge","VIP Darshan","Personal expenses"], itinerary: [{ day: "Day 1-3", title: "Arrival & Acclimatization", desc: "Arrive at Kathmandu/Lucknow. Acclimatization, medical check, permit processing." },{ day: "Day 4-6", title: "Journey to Tibet", desc: "Cross into Tibet. Drive through stunning Himalayan landscapes to Saga." },{ day: "Day 7-8", title: "Mansarovar Lake", desc: "Arrive at Lake Mansarovar. Holy dip, prayers, and overnight stay by the sacred lake." },{ day: "Day 9-11", title: "Kailash Parikrama", desc: "Begin the 52km circumambulation of Mt. Kailash over 3 days. Cross Dolma La Pass (5630m)." },{ day: "Day 12-13", title: "Return Journey", desc: "Drive back through Tibet. Cross back into Nepal/India." },{ day: "Day 14-15", title: "Departure", desc: "Return to Kathmandu/Lucknow. Departure with divine blessings." }] },
  kerala_group: { name: "Kerala Group Tour", subtitle: "Kochi - Munnar - Alleppey - Kovalam", price: "6,999", rawPrice: 6999, days: "5 Days / 4 Nights", badge: "GROUP TOUR", badgeColor: "#059669", img: "https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?w=1200&q=80", about: "Kerala - God Own Country - is a tropical paradise on India southwest coast. Famous for its backwaters, hill stations, beaches, and Ayurvedic treatments.", experience: [{ icon: "boat", title: "Houseboat Stay", desc: "Spend a night on a traditional Kerala houseboat gliding through the backwaters of Alleppey" },{ icon: "leaf", title: "Munnar Tea Gardens", desc: "Walk through endless rolling tea gardens in Munnar" },{ icon: "beach", title: "Kovalam Beach", desc: "Relax on the crescent-shaped Kovalam Beach" },{ icon: "elephant", title: "Elephant Encounter", desc: "Meet majestic elephants at Kodanad Elephant Training Centre" },{ icon: "spa", title: "Ayurvedic Spa", desc: "Rejuvenate with traditional Kerala Ayurvedic massage and treatments" },{ icon: "waterfall", title: "Athirappilly Falls", desc: "Visit Athirappilly - the Niagara of India, Kerala largest waterfall" }], gallery: ["https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?w=600&q=80","https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=600&q=80","https://images.unsplash.com/photo-1476514525535-07fb3b4ae5f1?w=600&q=80","https://images.unsplash.com/photo-1530789253388-582c481c54b0?w=600&q=80","https://images.unsplash.com/photo-1519451241324-20b4ea2c4220?w=600&q=80","https://images.unsplash.com/photo-1518621736915-f3b1c41bfd00?w=600&q=80"], inclusions: ["4 nights accommodation","Daily breakfast","Houseboat stay with meals","AC vehicle","Expert guide","Flight tickets / Train tickets"], exclusions: ["Auto charge","VIP Darshan","Personal expenses"], itinerary: [{ day: "Day 1", title: "Arrival Kochi", desc: "Arrive at Kochi. Check-in. Visit Fort Kochi, Chinese Fishing Nets, Mattancherry Palace." },{ day: "Day 2", title: "Munnar", desc: "Drive to Munnar. Visit Athirappilly Falls, tea gardens, Eravikulam National Park." },{ day: "Day 3", title: "Alleppey Houseboat", desc: "Drive to Alleppey. Board houseboat. Cruise through backwaters. Overnight on houseboat." },{ day: "Day 4", title: "Kovalam Beach", desc: "Drive to Kovalam. Beach time, Ayurvedic massage, Lighthouse Beach sunset." },{ day: "Day 5", title: "Departure", desc: "Morning free. Transfer to Trivandrum airport/station. Departure." }] },
  kerala_honeymoon: { name: "Kerala Honeymoon", subtitle: "Kochi - Munnar - Alleppey - Varkala", price: "25,999", rawPrice: 25999, days: "5 Days / 4 Nights", badge: "HONEYMOON", badgeColor: "#db2777", img: "https://images.unsplash.com/photo-1518621736915-f3b1c41bfd00?w=1200&q=80", about: "Kerala is the perfect honeymoon destination - romantic backwaters, misty hill stations, pristine beaches, and luxurious Ayurvedic resorts.", experience: [{ icon: "boat", title: "Private Houseboat", desc: "Exclusive private houseboat cruise through the romantic backwaters of Alleppey" },{ icon: "sunset", title: "Varkala Cliffs", desc: "Watch the breathtaking sunset from the dramatic red laterite cliffs of Varkala" },{ icon: "spa", title: "Couples Ayurveda", desc: "Indulge in a romantic couples Ayurvedic massage and spa treatment" },{ icon: "mist", title: "Munnar Mist", desc: "Wake up to misty mornings in Munnar" },{ icon: "dinner", title: "Candlelight Dinner", desc: "Romantic candlelight dinner by the backwaters or beach" },{ icon: "beach", title: "Beach Walks", desc: "Long romantic walks on the pristine beaches of Varkala and Kovalam" }], gallery: ["https://images.unsplash.com/photo-1518621736915-f3b1c41bfd00?w=600&q=80","https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?w=600&q=80","https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=600&q=80","https://images.unsplash.com/photo-1476514525535-07fb3b4ae5f1?w=600&q=80","https://images.unsplash.com/photo-1519451241324-20b4ea2c4220?w=600&q=80","https://images.unsplash.com/photo-1530789253388-582c481c54b0?w=600&q=80"], inclusions: ["4 nights accommodation (couple rooms)","Daily breakfast","Private houseboat with all meals","AC vehicle","Candlelight dinner (1 night)","Couples Ayurvedic massage","Flight tickets / Train tickets"], exclusions: ["Auto charge","VIP Darshan","Personal expenses"], itinerary: [{ day: "Day 1", title: "Arrival Kochi", desc: "Arrive at Kochi. Check-in to couple room. Evening - Fort Kochi walk, Chinese Fishing Nets." },{ day: "Day 2", title: "Munnar", desc: "Drive to Munnar. Tea garden walk, Eravikulam National Park, romantic dinner." },{ day: "Day 3", title: "Alleppey Houseboat", desc: "Drive to Alleppey. Private houseboat cruise. Romantic dinner on the backwaters." },{ day: "Day 4", title: "Varkala", desc: "Drive to Varkala. Cliff walk, beach time, sunset, Ayurvedic spa." },{ day: "Day 5", title: "Departure", desc: "Morning free. Transfer to Trivandrum airport/station. Departure." }] },
  goa: { name: "Goa Friends Package", subtitle: "North Goa - South Goa - Beaches", price: "9,999", rawPrice: 9999, days: "4 Days / 3 Nights", badge: "FRIENDS TRIP", badgeColor: "#0284c7", img: "https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?w=1200&q=80", about: "Goa is India party capital and beach paradise - a perfect destination for friends. With its stunning beaches, vibrant nightlife, Portuguese heritage, water sports, and delicious seafood.", experience: [{ icon: "beach", title: "Beach Hopping", desc: "Visit Calangute, Baga, Anjuna, and Vagator beaches" },{ icon: "dive", title: "Water Sports", desc: "Try jet skiing, parasailing, banana boat rides, and scuba diving" },{ icon: "sunset", title: "Sunset Cruise", desc: "Enjoy a sunset cruise on the Mandovi River with music and drinks" },{ icon: "fort", title: "Fort Aguada", desc: "Explore the 17th century Portuguese Fort Aguada" },{ icon: "food", title: "Beach Shacks", desc: "Relax at famous beach shacks with fresh seafood, cocktails, and live music" },{ icon: "dance", title: "Nightlife", desc: "Experience Goa legendary nightlife" }], gallery: ["https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?w=600&q=80","https://images.unsplash.com/photo-1587922546307-776227941871?w=600&q=80","https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=600&q=80","https://images.unsplash.com/photo-1519451241324-20b4ea2c4220?w=600&q=80","https://images.unsplash.com/photo-1476514525535-07fb3b4ae5f1?w=600&q=80","https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=600&q=80"], inclusions: ["3 nights hotel accommodation","Daily breakfast","AC vehicle","North & South Goa sightseeing","Beach activities","Flight tickets / Train tickets"], exclusions: ["Auto charge","VIP Darshan","Personal expenses"], itinerary: [{ day: "Day 1", title: "Arrival Goa", desc: "Arrive at Goa airport/station. Check-in. Evening - Calangute Beach, beach shacks." },{ day: "Day 2", title: "North Goa", desc: "Visit Baga Beach, Fort Aguada, Anjuna Flea Market, Chapora Fort, Vagator Beach." },{ day: "Day 3", title: "South Goa & Cruise", desc: "Visit Palolem Beach, Colva Beach, Dudhsagar Falls. Evening - Sunset Cruise on Mandovi River." },{ day: "Day 4", title: "Departure", desc: "Morning free for shopping at Mapusa Market. Transfer to airport/station." }] }
}

export default function PackageDetail() {
  const { id } = useParams()
  const navigate = useNavigate()
  const pkg = PACKAGE_DATA[id]
  const [members, setMembers] = useState(2)
  const [openDay, setOpenDay] = useState(null)
  const [lightbox, setLightbox] = useState(null)
  useSEO(pkg ? { title: pkg.name, description: pkg.about, keywords: `${pkg.name.toLowerCase()} tour package, ${pkg.subtitle.toLowerCase()}, saravana travels coimbatore`, url: `https://saravanatravels.in/package/${id}` } : {})
  useEffect(() => { window.scrollTo(0, 0) }, [id])
  if (!pkg) return (
    <div style={{ background: "#0a0f1e", minHeight: "100vh", display: "flex", alignItems: "center", justifyContent: "center", color: "white" }}>
      <div style={{ textAlign: "center" }}>
        <h2 style={{ fontSize: 24, fontWeight: "bold", margin: "12px 0" }}>Package not found</h2>
        <button onClick={() => navigate("/")} style={{ background: "#f97316", color: "white", padding: "10px 24px", borderRadius: 12, border: "none", cursor: "pointer", fontWeight: "bold" }}>Go Home</button>
      </div>
    </div>
  )
  const isContactOnly = pkg.rawPrice === 0
  const total = isContactOnly ? null : (pkg.rawPrice * members).toLocaleString("en-IN")
  const waMsg = isContactOnly
    ? encodeURIComponent("Hi! I am interested in *" + pkg.name + "*. Please share pricing and availability.")
    : encodeURIComponent("Hi! I want to book *" + pkg.name + "* for *" + members + " member" + (members > 1 ? "s" : "") + "*.\nTotal: Rs." + total + "\nPlease confirm availability.")
  const S = {
    page: { background: "#0a0f1e", minHeight: "100vh", color: "#fff" },
    heroWrap: { position: "relative", height: "100vh", minHeight: 500, overflow: "hidden" },
    heroImg: { width: "100%", height: "100%", objectFit: "cover", objectPosition: "center 20%", position: "absolute", inset: 0 },
    heroOverlay: { position: "absolute", inset: 0, background: "linear-gradient(to bottom, rgba(0,0,20,0.3) 0%, rgba(0,0,20,0.7) 60%, rgba(0,0,20,0.95) 100%)" },
    backBtn: { position: "absolute", top: 72, left: 16, background: "rgba(255,255,255,0.15)", backdropFilter: "blur(8px)", color: "white", padding: "8px 18px", borderRadius: 12, border: "1px solid rgba(255,255,255,0.2)", fontWeight: 600, cursor: "pointer", fontSize: 14 },
    heroBottom: { position: "absolute", bottom: 40, left: 0, right: 0, padding: "0 20px" },
    badge: { fontSize: 11, fontWeight: "bold", padding: "4px 14px", borderRadius: 999, display: "inline-block", marginBottom: 12, color: "white" },
    heroTitle: { fontSize: "clamp(28px, 6vw, 52px)", fontWeight: 800, margin: "0 0 8px", lineHeight: 1.1 },
    heroSub: { color: "#fdba74", fontSize: 15, margin: "0 0 16px" },
    heroBadges: { display: "flex", gap: 10, flexWrap: "wrap" },
    heroBadgeItem: { background: "rgba(255,255,255,0.12)", backdropFilter: "blur(8px)", border: "1px solid rgba(255,255,255,0.2)", borderRadius: 20, padding: "6px 14px", fontSize: 13, color: "white" },
    wrap: { maxWidth: 800, margin: "0 auto", padding: "40px 16px 60px" },
    divider: { height: 1, background: "rgba(255,255,255,0.08)", margin: "32px 0" },
    sectionTitle: { color: "#fb923c", fontSize: 20, fontWeight: 700, marginBottom: 16, marginTop: 0 },
    about: { color: "#d1d5db", fontSize: 14, lineHeight: 1.8 },
    expGrid: { display: "grid", gridTemplateColumns: "repeat(auto-fill, minmax(220px, 1fr))", gap: 12 },
    expCard: { background: "rgba(255,255,255,0.05)", border: "1px solid rgba(255,255,255,0.08)", borderRadius: 16, padding: 16 },
    galleryGrid: { display: "grid", gridTemplateColumns: "repeat(3, 1fr)", gap: 8 },
    galleryImg: { width: "100%", aspectRatio: "1", objectFit: "cover", borderRadius: 12, cursor: "pointer" },
    incExcGrid: { display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(240px, 1fr))", gap: 16 },
    itinBtn: { width: "100%", display: "flex", justifyContent: "space-between", alignItems: "center", padding: "14px 16px", border: "none", color: "white", cursor: "pointer", fontSize: 14, fontWeight: 600, textAlign: "left" },
    bookBox: { background: "rgba(255,255,255,0.06)", border: "1px solid rgba(251,146,60,0.35)", borderRadius: 20, padding: 24, backdropFilter: "blur(12px)" },
    waBtn: { display: "block", width: "100%", textAlign: "center", background: "#22c55e", color: "white", fontWeight: 700, padding: 16, borderRadius: 16, fontSize: 16, textDecoration: "none", boxSizing: "border-box" },
    lightboxOverlay: { position: "fixed", inset: 0, background: "rgba(0,0,0,0.92)", zIndex: 9999, display: "flex", alignItems: "center", justifyContent: "center" },
    lightboxImg: { maxWidth: "90vw", maxHeight: "85vh", borderRadius: 12, objectFit: "contain" },
    lightboxClose: { position: "absolute", top: 20, right: 24, color: "white", fontSize: 32, cursor: "pointer", background: "none", border: "none" }
  }
  return (
    <div style={S.page}>
      {lightbox !== null && (
        <div style={S.lightboxOverlay} onClick={() => setLightbox(null)}>
          <button style={S.lightboxClose} onClick={() => setLightbox(null)}>X</button>
          <img src={pkg.gallery[lightbox]} alt="" style={S.lightboxImg} onClick={e => e.stopPropagation()} />
        </div>
      )}
      <div style={S.heroWrap}>
        <img src="/siva.png" alt="bg" style={S.heroImg} />
        <div style={S.heroOverlay} />
        <button onClick={() => navigate(-1)} style={S.backBtn}>Back</button>
        <div style={S.heroBottom}>
          <div style={{ maxWidth: 800, margin: "0 auto" }}>
            <span style={{ ...S.badge, background: pkg.badgeColor }}>{pkg.badge}</span>
            <h1 style={S.heroTitle}>{pkg.name}</h1>
            <p style={S.heroSub}>{pkg.subtitle}</p>
            <div style={S.heroBadges}>
              <span style={S.heroBadgeItem}>{pkg.days}</span>
              <span style={S.heroBadgeItem}>{isContactOnly ? "Contact for price" : "Rs." + pkg.price + " / person"}</span>
              <span style={S.heroBadgeItem}>✅ Tamilnadu Meals</span>
              <span style={S.heroBadgeItem}>✅ Flight / Train Tickets</span>
              <span style={S.heroBadgeItem}>✅ AC Transport</span>
              <span style={{...S.heroBadgeItem, background: "rgba(220,38,38,0.25)", border: "1px solid rgba(220,38,38,0.5)", color: "#fca5a5"}}>❌ Auto Charge</span>
              <span style={{...S.heroBadgeItem, background: "rgba(220,38,38,0.25)", border: "1px solid rgba(220,38,38,0.5)", color: "#fca5a5"}}>❌ VIP Darshan</span>
              <span style={{...S.heroBadgeItem, background: "rgba(220,38,38,0.25)", border: "1px solid rgba(220,38,38,0.5)", color: "#fca5a5"}}>❌ Personal Expenses</span>
            </div>
          </div>
        </div>
      </div>
      <div style={{ background: "#0a0f1e" }}>
        <div style={S.wrap}>
          <p style={S.about}>{pkg.about}</p>
          <div style={S.divider} />
          <h2 style={S.sectionTitle}>Your Experience</h2>
          <div style={S.expGrid}>
            {pkg.experience.map((e, i) => (
              <div key={i} style={S.expCard}>
                <div style={{ fontWeight: 700, fontSize: 14, color: "white", marginBottom: 4 }}>{e.title}</div>
                <div style={{ fontSize: 12, color: "#9ca3af", lineHeight: 1.5 }}>{e.desc}</div>
              </div>
            ))}
          </div>
          <div style={S.divider} />
          <h2 style={S.sectionTitle}>Photo Gallery</h2>
          <div style={S.galleryGrid}>
            {pkg.gallery.map((src, i) => (
              <img key={i} src={src} alt={"gallery " + i} style={S.galleryImg} onClick={() => setLightbox(i)} />
            ))}
          </div>
          <div style={S.divider} />
          <h2 style={S.sectionTitle}>Inclusions & Exclusions</h2>
          <div style={S.incExcGrid}>
            <div style={{ background: "rgba(20,83,45,0.3)", border: "1px solid rgba(74,222,128,0.2)", borderRadius: 16, padding: 16 }}>
              <h3 style={{ color: "#4ade80", fontWeight: 700, marginBottom: 10, fontSize: 15, marginTop: 0 }}>Included</h3>
              {pkg.inclusions.map((inc, i) => <p key={i} style={{ color: "#4ade80", fontSize: 13, margin: "5px 0", fontWeight: 500 }}>✓ {inc}</p>)}
            </div>
            <div style={{ background: "rgba(127,29,29,0.3)", border: "1px solid rgba(248,113,113,0.2)", borderRadius: 16, padding: 16 }}>
              <h3 style={{ color: "#f87171", fontWeight: 700, marginBottom: 10, fontSize: 15, marginTop: 0 }}>Not Included</h3>
              {pkg.exclusions.map((exc, i) => <p key={i} style={{ color: "#f87171", fontSize: 13, margin: "5px 0", fontWeight: 600 }}>✗ {exc}</p>)}
            </div>
          </div>
          <div style={S.divider} />
          <h2 style={S.sectionTitle}>Day-by-Day Itinerary</h2>
          <div style={{ display: "flex", flexDirection: "column", gap: 8 }}>
            {pkg.itinerary.map((item, i) => (
              <div key={i} style={{ borderRadius: 12, overflow: "hidden", border: "1px solid rgba(255,255,255,0.1)" }}>
                <button onClick={() => setOpenDay(openDay === i ? null : i)} style={{ ...S.itinBtn, background: openDay === i ? "rgba(251,146,60,0.15)" : "rgba(255,255,255,0.04)" }}>
                  <span><span style={{ color: "#fb923c", marginRight: 8 }}>{item.day}</span>{item.title}</span>
                  <span style={{ color: "#fb923c", fontSize: 12 }}>{openDay === i ? "^" : "v"}</span>
                </button>
                {openDay === i && <div style={{ padding: "12px 16px", background: "rgba(255,255,255,0.02)", color: "#d1d5db", fontSize: 13, lineHeight: 1.7 }}>{item.desc}</div>}
              </div>
            ))}
          </div>
          <div style={S.divider} />
          <div style={S.bookBox}>
            <h2 style={{ color: "#fb923c", fontSize: 20, fontWeight: 700, marginBottom: 20, marginTop: 0 }}>Book This Package</h2>
            {!isContactOnly && (
              <div style={{ marginBottom: 20 }}>
                <div style={{ display: "flex", justifyContent: "space-between", color: "#d1d5db", fontSize: 14, marginBottom: 10 }}>
                  <span>Number of Members</span>
                  <span style={{ fontWeight: 800, color: "white", fontSize: 22 }}>{members}</span>
                </div>
                <input type="range" min={1} max={50} value={members} onChange={e => setMembers(Number(e.target.value))} style={{ width: "100%", accentColor: "#f97316", cursor: "pointer" }} />
                <div style={{ display: "flex", justifyContent: "space-between", color: "#6b7280", fontSize: 12, marginTop: 4 }}>
                  <span>1</span><span>25</span><span>50</span>
                </div>
              </div>
            )}
            {!isContactOnly && (
              <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", background: "rgba(0,0,0,0.3)", borderRadius: 14, padding: "14px 18px", marginBottom: 20 }}>
                <div>
                  <p style={{ color: "#9ca3af", fontSize: 12, margin: 0 }}>Per person</p>
                  <p style={{ color: "#4ade80", fontWeight: 700, fontSize: 20, margin: 0 }}>Rs.{pkg.price}</p>
                </div>
                <div style={{ textAlign: "right" }}>
                  <p style={{ color: "#9ca3af", fontSize: 12, margin: 0 }}>Total for {members} member{members > 1 ? "s" : ""}</p>
                  <p style={{ color: "white", fontWeight: 800, fontSize: 28, margin: 0 }}>Rs.{total}</p>
                </div>
              </div>
            )}
            {isContactOnly && (
              <div style={{ background: "rgba(124,58,237,0.2)", border: "1px solid rgba(124,58,237,0.4)", borderRadius: 14, padding: "14px 18px", marginBottom: 20, textAlign: "center" }}>
                <p style={{ color: "#c4b5fd", fontSize: 14, margin: 0 }}>This is a premium package. Contact us for custom pricing based on your group size and requirements.</p>
              </div>
            )}
            <a href={"https://wa.me/918838691200?text=" + waMsg} target="_blank" rel="noreferrer" style={S.waBtn}>
              {isContactOnly ? "Enquire on WhatsApp" : "Book via WhatsApp"}
            </a>
            <p style={{ textAlign: "center", color: "#6b7280", fontSize: 12, marginTop: 10, marginBottom: 0 }}>We will confirm availability within 2 hours</p>
          </div>
        </div>
      </div>
    </div>
  )
}